/// <reference types="$lib/server/rust/index" />

/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Find the next fibonacci sequence number */
export declare function fibonacci(n: number): number;

export interface SettledInfo {
	data: Array<SettledTrade>;
	totalBuy: number;
	totalBuyClients: number;
	totalSell: number;
	totalSellClients: number;
	netVal: number;
	date: number;
}

export interface SettledTrade {
	csdRef: string;
	brokerRef: string;
	luseId: number;
	symbol: string;
	price: number;
	qty: number;
	value: number;
	counterFirm: string;
	/** `buy` or `sell` */
	side: string;
	date: number;
}

/** handle the settlement report; based on *7 Oct 2025* settlement report */
export declare function settleV1(rawStr: string): SettledInfo;
