[package]
name = "rust"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version="3", features=["async"]}
napi-derive = "3"
rust_decimal = "1.37.2"

[build-dependencies]
napi-build = "1"