drop policy "service_only" on "public"."otps";


  create table "public"."odyn-chats" (
    "id" bigint generated by default as identity not null,
    "ticket_no" text not null,
    "sender" text not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."odyn-chats" enable row level security;


  create table "public"."odyn-history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ticket_no" text not null,
    "creator" text not null,
    "message" text not null
      );


alter table "public"."odyn-history" enable row level security;

alter table "public"."odyn-tickets" add column "closed_by" text;

alter table "public"."odyn-tickets" add column "email_vars" text;

alter table "public"."odyn-tickets" add column "is_client" boolean not null default false;

CREATE UNIQUE INDEX "odyn-chats_id_key" ON public."odyn-chats" USING btree (id);

CREATE UNIQUE INDEX "odyn-chats_pkey" ON public."odyn-chats" USING btree (id);

CREATE UNIQUE INDEX "odyn-history_pkey" ON public."odyn-history" USING btree (id);

alter table "public"."odyn-chats" add constraint "odyn-chats_pkey" PRIMARY KEY using index "odyn-chats_pkey";

alter table "public"."odyn-history" add constraint "odyn-history_pkey" PRIMARY KEY using index "odyn-history_pkey";

alter table "public"."odyn-chats" add constraint "odyn-chats_id_key" UNIQUE using index "odyn-chats_id_key";

grant delete on table "public"."odyn-chats" to "anon";

grant insert on table "public"."odyn-chats" to "anon";

grant references on table "public"."odyn-chats" to "anon";

grant select on table "public"."odyn-chats" to "anon";

grant trigger on table "public"."odyn-chats" to "anon";

grant truncate on table "public"."odyn-chats" to "anon";

grant update on table "public"."odyn-chats" to "anon";

grant delete on table "public"."odyn-chats" to "authenticated";

grant insert on table "public"."odyn-chats" to "authenticated";

grant references on table "public"."odyn-chats" to "authenticated";

grant select on table "public"."odyn-chats" to "authenticated";

grant trigger on table "public"."odyn-chats" to "authenticated";

grant truncate on table "public"."odyn-chats" to "authenticated";

grant update on table "public"."odyn-chats" to "authenticated";

grant delete on table "public"."odyn-chats" to "service_role";

grant insert on table "public"."odyn-chats" to "service_role";

grant references on table "public"."odyn-chats" to "service_role";

grant select on table "public"."odyn-chats" to "service_role";

grant trigger on table "public"."odyn-chats" to "service_role";

grant truncate on table "public"."odyn-chats" to "service_role";

grant update on table "public"."odyn-chats" to "service_role";

grant delete on table "public"."odyn-history" to "anon";

grant insert on table "public"."odyn-history" to "anon";

grant references on table "public"."odyn-history" to "anon";

grant select on table "public"."odyn-history" to "anon";

grant trigger on table "public"."odyn-history" to "anon";

grant truncate on table "public"."odyn-history" to "anon";

grant update on table "public"."odyn-history" to "anon";

grant delete on table "public"."odyn-history" to "authenticated";

grant insert on table "public"."odyn-history" to "authenticated";

grant references on table "public"."odyn-history" to "authenticated";

grant select on table "public"."odyn-history" to "authenticated";

grant trigger on table "public"."odyn-history" to "authenticated";

grant truncate on table "public"."odyn-history" to "authenticated";

grant update on table "public"."odyn-history" to "authenticated";

grant delete on table "public"."odyn-history" to "service_role";

grant insert on table "public"."odyn-history" to "service_role";

grant references on table "public"."odyn-history" to "service_role";

grant select on table "public"."odyn-history" to "service_role";

grant trigger on table "public"."odyn-history" to "service_role";

grant truncate on table "public"."odyn-history" to "service_role";

grant update on table "public"."odyn-history" to "service_role";


  create policy "service_only"
  on "public"."odyn-chats"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-history"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."otps"
  as permissive
  for all
  to service_role
using (true);



