drop extension if exists "pg_net";


  create table "public"."admins" (
    "username" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text not null,
    "full_names" text not null,
    "phone" text not null,
    "email" text not null,
    "permissions" text not null,
    "department" text not null,
    "ticketable" boolean not null default true
      );


alter table "public"."admins" enable row level security;


  create table "public"."clients" (
    "luseId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "fname" text not null,
    "lname" text not null,
    "phone" bigint not null,
    "email" text not null,
    "dob" timestamp with time zone not null,
    "gender" text not null,
    "mstatus" text not null,
    "nationality" text not null,
    "street" text not null,
    "city" text not null,
    "id_type" text not null,
    "id_num" text not null,
    "bank_name" text not null,
    "bank_acc_name" text not null,
    "bank_acc_num" text not null,
    "branch_name" text not null,
    "branch_code" text not null,
    "swift_code" text not null,
    "acc_type" text not null,
    "manag_fname" text not null,
    "manag_lname" text not null,
    "manag_phone" bigint not null,
    "manag_email" text not null,
    "manag_dob" timestamp with time zone not null,
    "manag_gender" text not null,
    "manag_mstatus" text not null,
    "manag_nationality" text not null,
    "manag_street" text not null,
    "manag_city" text not null,
    "manag_country" text not null,
    "manag_id_type" text not null,
    "manag_id_num" text not null,
    "is_in_trust_of" boolean not null default false,
    "joint_partners" jsonb[] not null,
    "comp_directors" jsonb[] not null,
    "comp_managers" jsonb[] not null,
    "is_approved" boolean not null default false,
    "signatures" jsonb not null
      );


alter table "public"."clients" enable row level security;


  create table "public"."logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "value" text not null
      );


alter table "public"."logs" enable row level security;


  create table "public"."odyn-tickets" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "names" text not null,
    "phone" text not null,
    "email" text not null,
    "id_num" bigint not null,
    "luse_id" bigint not null,
    "query_type" text not null,
    "query" text not null,
    "assigned" text not null,
    "is_closed" boolean not null default false,
    "close_date" timestamp with time zone,
    "object" jsonb
      );


alter table "public"."odyn-tickets" enable row level security;


  create table "public"."system-vars" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null,
    "value" text not null
      );


alter table "public"."system-vars" enable row level security;

CREATE UNIQUE INDEX admins_pkey ON public.admins USING btree (username);

CREATE UNIQUE INDEX "clients_luseId_key" ON public.clients USING btree ("luseId");

CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree ("luseId");

CREATE UNIQUE INDEX "odyn-tickets_pkey" ON public."odyn-tickets" USING btree (id);

CREATE UNIQUE INDEX "system-vars_pkey" ON public."system-vars" USING btree (id);

CREATE UNIQUE INDEX tickets_pkey ON public.logs USING btree (id);

alter table "public"."admins" add constraint "admins_pkey" PRIMARY KEY using index "admins_pkey";

alter table "public"."clients" add constraint "clients_pkey" PRIMARY KEY using index "clients_pkey";

alter table "public"."logs" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."odyn-tickets" add constraint "odyn-tickets_pkey" PRIMARY KEY using index "odyn-tickets_pkey";

alter table "public"."system-vars" add constraint "system-vars_pkey" PRIMARY KEY using index "system-vars_pkey";

alter table "public"."clients" add constraint "clients_luseId_key" UNIQUE using index "clients_luseId_key";

grant delete on table "public"."admins" to "anon";

grant insert on table "public"."admins" to "anon";

grant references on table "public"."admins" to "anon";

grant select on table "public"."admins" to "anon";

grant trigger on table "public"."admins" to "anon";

grant truncate on table "public"."admins" to "anon";

grant update on table "public"."admins" to "anon";

grant delete on table "public"."admins" to "authenticated";

grant insert on table "public"."admins" to "authenticated";

grant references on table "public"."admins" to "authenticated";

grant select on table "public"."admins" to "authenticated";

grant trigger on table "public"."admins" to "authenticated";

grant truncate on table "public"."admins" to "authenticated";

grant update on table "public"."admins" to "authenticated";

grant delete on table "public"."admins" to "service_role";

grant insert on table "public"."admins" to "service_role";

grant references on table "public"."admins" to "service_role";

grant select on table "public"."admins" to "service_role";

grant trigger on table "public"."admins" to "service_role";

grant truncate on table "public"."admins" to "service_role";

grant update on table "public"."admins" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."logs" to "anon";

grant insert on table "public"."logs" to "anon";

grant references on table "public"."logs" to "anon";

grant select on table "public"."logs" to "anon";

grant trigger on table "public"."logs" to "anon";

grant truncate on table "public"."logs" to "anon";

grant update on table "public"."logs" to "anon";

grant delete on table "public"."logs" to "authenticated";

grant insert on table "public"."logs" to "authenticated";

grant references on table "public"."logs" to "authenticated";

grant select on table "public"."logs" to "authenticated";

grant trigger on table "public"."logs" to "authenticated";

grant truncate on table "public"."logs" to "authenticated";

grant update on table "public"."logs" to "authenticated";

grant delete on table "public"."logs" to "service_role";

grant insert on table "public"."logs" to "service_role";

grant references on table "public"."logs" to "service_role";

grant select on table "public"."logs" to "service_role";

grant trigger on table "public"."logs" to "service_role";

grant truncate on table "public"."logs" to "service_role";

grant update on table "public"."logs" to "service_role";

grant delete on table "public"."odyn-tickets" to "anon";

grant insert on table "public"."odyn-tickets" to "anon";

grant references on table "public"."odyn-tickets" to "anon";

grant select on table "public"."odyn-tickets" to "anon";

grant trigger on table "public"."odyn-tickets" to "anon";

grant truncate on table "public"."odyn-tickets" to "anon";

grant update on table "public"."odyn-tickets" to "anon";

grant delete on table "public"."odyn-tickets" to "authenticated";

grant insert on table "public"."odyn-tickets" to "authenticated";

grant references on table "public"."odyn-tickets" to "authenticated";

grant select on table "public"."odyn-tickets" to "authenticated";

grant trigger on table "public"."odyn-tickets" to "authenticated";

grant truncate on table "public"."odyn-tickets" to "authenticated";

grant update on table "public"."odyn-tickets" to "authenticated";

grant delete on table "public"."odyn-tickets" to "service_role";

grant insert on table "public"."odyn-tickets" to "service_role";

grant references on table "public"."odyn-tickets" to "service_role";

grant select on table "public"."odyn-tickets" to "service_role";

grant trigger on table "public"."odyn-tickets" to "service_role";

grant truncate on table "public"."odyn-tickets" to "service_role";

grant update on table "public"."odyn-tickets" to "service_role";

grant delete on table "public"."system-vars" to "anon";

grant insert on table "public"."system-vars" to "anon";

grant references on table "public"."system-vars" to "anon";

grant select on table "public"."system-vars" to "anon";

grant trigger on table "public"."system-vars" to "anon";

grant truncate on table "public"."system-vars" to "anon";

grant update on table "public"."system-vars" to "anon";

grant delete on table "public"."system-vars" to "authenticated";

grant insert on table "public"."system-vars" to "authenticated";

grant references on table "public"."system-vars" to "authenticated";

grant select on table "public"."system-vars" to "authenticated";

grant trigger on table "public"."system-vars" to "authenticated";

grant truncate on table "public"."system-vars" to "authenticated";

grant update on table "public"."system-vars" to "authenticated";

grant delete on table "public"."system-vars" to "service_role";

grant insert on table "public"."system-vars" to "service_role";

grant references on table "public"."system-vars" to "service_role";

grant select on table "public"."system-vars" to "service_role";

grant trigger on table "public"."system-vars" to "service_role";

grant truncate on table "public"."system-vars" to "service_role";

grant update on table "public"."system-vars" to "service_role";


