
  create table "public"."csd-clients-temp" (
    "luse_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "names" text not null
      );


alter table "public"."csd-clients-temp" enable row level security;


  create table "public"."odyn-socials" (
    "id" bigint generated by default as identity not null,
    "date" timestamp with time zone not null,
    "platform" text not null,
    "metric" text not null,
    "value" bigint not null
      );


alter table "public"."odyn-socials" enable row level security;


  create table "public"."settled_trades" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" bigint not null,
    "csd_ref" text not null,
    "broker_ref" text not null,
    "luse_id" bigint not null,
    "names" text not null,
    "symbol" text not null,
    "price" double precision not null,
    "qty" bigint not null,
    "value" double precision not null,
    "counter_firm" text not null,
    "side" text not null
      );


alter table "public"."settled_trades" enable row level security;

CREATE UNIQUE INDEX "csd-clients-temp_luse_id_key" ON public."csd-clients-temp" USING btree (luse_id);

CREATE UNIQUE INDEX "csd-clients-temp_pkey" ON public."csd-clients-temp" USING btree (luse_id);

CREATE UNIQUE INDEX "odyn-socials_pkey" ON public."odyn-socials" USING btree (id);

CREATE UNIQUE INDEX settled_trades_pkey ON public.settled_trades USING btree (id);

alter table "public"."csd-clients-temp" add constraint "csd-clients-temp_pkey" PRIMARY KEY using index "csd-clients-temp_pkey";

alter table "public"."odyn-socials" add constraint "odyn-socials_pkey" PRIMARY KEY using index "odyn-socials_pkey";

alter table "public"."settled_trades" add constraint "settled_trades_pkey" PRIMARY KEY using index "settled_trades_pkey";

alter table "public"."csd-clients-temp" add constraint "csd-clients-temp_luse_id_key" UNIQUE using index "csd-clients-temp_luse_id_key";

grant delete on table "public"."csd-clients-temp" to "anon";

grant insert on table "public"."csd-clients-temp" to "anon";

grant references on table "public"."csd-clients-temp" to "anon";

grant select on table "public"."csd-clients-temp" to "anon";

grant trigger on table "public"."csd-clients-temp" to "anon";

grant truncate on table "public"."csd-clients-temp" to "anon";

grant update on table "public"."csd-clients-temp" to "anon";

grant delete on table "public"."csd-clients-temp" to "authenticated";

grant insert on table "public"."csd-clients-temp" to "authenticated";

grant references on table "public"."csd-clients-temp" to "authenticated";

grant select on table "public"."csd-clients-temp" to "authenticated";

grant trigger on table "public"."csd-clients-temp" to "authenticated";

grant truncate on table "public"."csd-clients-temp" to "authenticated";

grant update on table "public"."csd-clients-temp" to "authenticated";

grant delete on table "public"."csd-clients-temp" to "service_role";

grant insert on table "public"."csd-clients-temp" to "service_role";

grant references on table "public"."csd-clients-temp" to "service_role";

grant select on table "public"."csd-clients-temp" to "service_role";

grant trigger on table "public"."csd-clients-temp" to "service_role";

grant truncate on table "public"."csd-clients-temp" to "service_role";

grant update on table "public"."csd-clients-temp" to "service_role";

grant delete on table "public"."odyn-socials" to "anon";

grant insert on table "public"."odyn-socials" to "anon";

grant references on table "public"."odyn-socials" to "anon";

grant select on table "public"."odyn-socials" to "anon";

grant trigger on table "public"."odyn-socials" to "anon";

grant truncate on table "public"."odyn-socials" to "anon";

grant update on table "public"."odyn-socials" to "anon";

grant delete on table "public"."odyn-socials" to "authenticated";

grant insert on table "public"."odyn-socials" to "authenticated";

grant references on table "public"."odyn-socials" to "authenticated";

grant select on table "public"."odyn-socials" to "authenticated";

grant trigger on table "public"."odyn-socials" to "authenticated";

grant truncate on table "public"."odyn-socials" to "authenticated";

grant update on table "public"."odyn-socials" to "authenticated";

grant delete on table "public"."odyn-socials" to "service_role";

grant insert on table "public"."odyn-socials" to "service_role";

grant references on table "public"."odyn-socials" to "service_role";

grant select on table "public"."odyn-socials" to "service_role";

grant trigger on table "public"."odyn-socials" to "service_role";

grant truncate on table "public"."odyn-socials" to "service_role";

grant update on table "public"."odyn-socials" to "service_role";

grant delete on table "public"."settled_trades" to "anon";

grant insert on table "public"."settled_trades" to "anon";

grant references on table "public"."settled_trades" to "anon";

grant select on table "public"."settled_trades" to "anon";

grant trigger on table "public"."settled_trades" to "anon";

grant truncate on table "public"."settled_trades" to "anon";

grant update on table "public"."settled_trades" to "anon";

grant delete on table "public"."settled_trades" to "authenticated";

grant insert on table "public"."settled_trades" to "authenticated";

grant references on table "public"."settled_trades" to "authenticated";

grant select on table "public"."settled_trades" to "authenticated";

grant trigger on table "public"."settled_trades" to "authenticated";

grant truncate on table "public"."settled_trades" to "authenticated";

grant update on table "public"."settled_trades" to "authenticated";

grant delete on table "public"."settled_trades" to "service_role";

grant insert on table "public"."settled_trades" to "service_role";

grant references on table "public"."settled_trades" to "service_role";

grant select on table "public"."settled_trades" to "service_role";

grant trigger on table "public"."settled_trades" to "service_role";

grant truncate on table "public"."settled_trades" to "service_role";

grant update on table "public"."settled_trades" to "service_role";


  create policy "service_only"
  on "public"."csd-clients-temp"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-socials"
  as permissive
  for all
  to service_role
using (true);


CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


