drop extension if exists "pg_net";

create type "public"."account-type" as enum ('LI', 'LC', 'FI', 'FC');

create type "public"."message_type" as enum ('text', 'pdf', 'command', 'img');

create type "public"."read_status" as enum ('unread', 'read');


  create table "public"."admins" (
    "username" text not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" text not null,
    "full_names" text not null,
    "phone" text not null,
    "email" text not null,
    "permissions" text not null,
    "department" text not null,
    "ticketable" boolean not null default true,
    "approved" boolean not null default true
      );


alter table "public"."admins" enable row level security;


  create table "public"."clients" (
    "luseId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "fname" text not null,
    "lname" text not null,
    "phone" bigint not null,
    "email" text not null,
    "dob" timestamp with time zone not null,
    "gender" text not null,
    "mstatus" text not null,
    "nationality" text not null,
    "street" text not null,
    "city" text not null,
    "id_type" text not null,
    "id_num" text not null,
    "bank_name" text not null,
    "bank_acc_name" text not null,
    "bank_acc_num" text not null,
    "branch_name" text not null,
    "branch_code" text not null,
    "swift_code" text not null,
    "acc_type" text not null,
    "manag_fname" text not null,
    "manag_lname" text not null,
    "manag_phone" bigint not null,
    "manag_email" text not null,
    "manag_dob" timestamp with time zone not null,
    "manag_gender" text not null,
    "manag_mstatus" text not null,
    "manag_nationality" text not null,
    "manag_street" text not null,
    "manag_city" text not null,
    "manag_country" text not null,
    "manag_id_type" text not null,
    "manag_id_num" text not null,
    "is_in_trust_of" boolean not null default false,
    "joint_partners" jsonb[] not null,
    "comp_directors" jsonb[] not null,
    "comp_managers" jsonb[] not null,
    "is_approved" boolean not null default false,
    "signatures" jsonb not null,
    "country" text not null,
    "signing_arrangement" bigint not null default '1'::bigint,
    "cv_num" text not null,
    "broker_comission" double precision not null default '0.01'::double precision,
    "referral_src" text not null default ''::text,
    "approved_by" text not null default ''::text,
    "approve_date" timestamp with time zone
      );


alter table "public"."clients" enable row level security;


  create table "public"."deep-stats" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null,
    "value" double precision not null,
    "section" text not null,
    "sender" text not null
      );


alter table "public"."deep-stats" enable row level security;


  create table "public"."logs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "value" text not null
      );


alter table "public"."logs" enable row level security;


  create table "public"."odyn-cache" (
    "uid" text not null,
    "udf" text not null,
    "position" text not null
      );


alter table "public"."odyn-cache" enable row level security;


  create table "public"."odyn-chats" (
    "id" bigint generated by default as identity not null,
    "ticket_no" text not null,
    "sender" text not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now(),
    "type" message_type not null default 'text'::message_type
      );


alter table "public"."odyn-chats" enable row level security;


  create table "public"."odyn-history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "ticket_no" text not null,
    "creator" text not null,
    "message" text not null
      );


alter table "public"."odyn-history" enable row level security;


  create table "public"."odyn-socials" (
    "id" bigint generated by default as identity not null,
    "date" timestamp with time zone not null,
    "platform" text not null,
    "metric" text not null,
    "value" bigint not null
      );


alter table "public"."odyn-socials" enable row level security;


  create table "public"."odyn-tickets" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "names" text not null,
    "phone" text not null,
    "email" text not null,
    "id_num" text not null,
    "luse_id" bigint not null,
    "query_type" text not null,
    "query" text not null,
    "assigned" text not null,
    "is_closed" boolean not null default false,
    "close_date" timestamp with time zone,
    "object" jsonb,
    "platform" text not null,
    "referral_source" text not null,
    "uid" text not null,
    "closed_by" text,
    "email_vars" text,
    "is_client" boolean not null default false,
    "assignee_email_vars" text,
    "close_reason" text,
    "read_status" read_status not null default 'unread'::read_status
      );


alter table "public"."odyn-tickets" enable row level security;


  create table "public"."otps" (
    "id" text not null,
    "otp" bigint not null,
    "updated_at" timestamp with time zone not null
      );


alter table "public"."otps" enable row level security;


  create table "public"."settled_trades" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" bigint not null,
    "csd_ref" text not null,
    "broker_ref" text not null,
    "luse_id" bigint not null,
    "names" text not null,
    "symbol" text not null,
    "price" double precision not null,
    "qty" bigint not null,
    "value" double precision not null,
    "counter_firm" text not null,
    "side" text not null,
    "currency" text not null default 'zmw'::text,
    "sec_commision" double precision not null default '0.125'::double precision,
    "luse_comission" double precision not null default '0.375'::double precision,
    "trade_date" timestamp with time zone not null default now(),
    "broker_comission" double precision not null default '0.01'::double precision
      );


alter table "public"."settled_trades" enable row level security;


  create table "public"."system-vars" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "key" text not null,
    "value" text not null
      );


alter table "public"."system-vars" enable row level security;

CREATE UNIQUE INDEX admins_pkey ON public.admins USING btree (username);

CREATE UNIQUE INDEX "clients_luseId_key" ON public.clients USING btree ("luseId");

CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree ("luseId");

CREATE UNIQUE INDEX "deep-stats_pkey" ON public."deep-stats" USING btree (id);

CREATE UNIQUE INDEX "odyn-cache_pkey" ON public."odyn-cache" USING btree (uid);

CREATE UNIQUE INDEX "odyn-chats_id_key" ON public."odyn-chats" USING btree (id);

CREATE UNIQUE INDEX "odyn-chats_pkey" ON public."odyn-chats" USING btree (id);

CREATE UNIQUE INDEX "odyn-history_pkey" ON public."odyn-history" USING btree (id);

CREATE UNIQUE INDEX "odyn-socials_pkey" ON public."odyn-socials" USING btree (id);

CREATE UNIQUE INDEX "odyn-tickets_pkey" ON public."odyn-tickets" USING btree (id);

CREATE UNIQUE INDEX otps_id_key ON public.otps USING btree (id);

CREATE UNIQUE INDEX otps_pkey ON public.otps USING btree (id);

CREATE UNIQUE INDEX settled_trades_pkey ON public.settled_trades USING btree (id);

CREATE UNIQUE INDEX "system-vars_pkey" ON public."system-vars" USING btree (id);

CREATE UNIQUE INDEX tickets_pkey ON public.logs USING btree (id);

alter table "public"."admins" add constraint "admins_pkey" PRIMARY KEY using index "admins_pkey";

alter table "public"."clients" add constraint "clients_pkey" PRIMARY KEY using index "clients_pkey";

alter table "public"."deep-stats" add constraint "deep-stats_pkey" PRIMARY KEY using index "deep-stats_pkey";

alter table "public"."logs" add constraint "tickets_pkey" PRIMARY KEY using index "tickets_pkey";

alter table "public"."odyn-cache" add constraint "odyn-cache_pkey" PRIMARY KEY using index "odyn-cache_pkey";

alter table "public"."odyn-chats" add constraint "odyn-chats_pkey" PRIMARY KEY using index "odyn-chats_pkey";

alter table "public"."odyn-history" add constraint "odyn-history_pkey" PRIMARY KEY using index "odyn-history_pkey";

alter table "public"."odyn-socials" add constraint "odyn-socials_pkey" PRIMARY KEY using index "odyn-socials_pkey";

alter table "public"."odyn-tickets" add constraint "odyn-tickets_pkey" PRIMARY KEY using index "odyn-tickets_pkey";

alter table "public"."otps" add constraint "otps_pkey" PRIMARY KEY using index "otps_pkey";

alter table "public"."settled_trades" add constraint "settled_trades_pkey" PRIMARY KEY using index "settled_trades_pkey";

alter table "public"."system-vars" add constraint "system-vars_pkey" PRIMARY KEY using index "system-vars_pkey";

alter table "public"."clients" add constraint "clients_luseId_key" UNIQUE using index "clients_luseId_key";

alter table "public"."odyn-chats" add constraint "odyn-chats_id_key" UNIQUE using index "odyn-chats_id_key";

alter table "public"."otps" add constraint "otps_id_key" UNIQUE using index "otps_id_key";

grant delete on table "public"."admins" to "anon";

grant insert on table "public"."admins" to "anon";

grant references on table "public"."admins" to "anon";

grant select on table "public"."admins" to "anon";

grant trigger on table "public"."admins" to "anon";

grant truncate on table "public"."admins" to "anon";

grant update on table "public"."admins" to "anon";

grant delete on table "public"."admins" to "authenticated";

grant insert on table "public"."admins" to "authenticated";

grant references on table "public"."admins" to "authenticated";

grant select on table "public"."admins" to "authenticated";

grant trigger on table "public"."admins" to "authenticated";

grant truncate on table "public"."admins" to "authenticated";

grant update on table "public"."admins" to "authenticated";

grant delete on table "public"."admins" to "service_role";

grant insert on table "public"."admins" to "service_role";

grant references on table "public"."admins" to "service_role";

grant select on table "public"."admins" to "service_role";

grant trigger on table "public"."admins" to "service_role";

grant truncate on table "public"."admins" to "service_role";

grant update on table "public"."admins" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."deep-stats" to "anon";

grant insert on table "public"."deep-stats" to "anon";

grant references on table "public"."deep-stats" to "anon";

grant select on table "public"."deep-stats" to "anon";

grant trigger on table "public"."deep-stats" to "anon";

grant truncate on table "public"."deep-stats" to "anon";

grant update on table "public"."deep-stats" to "anon";

grant delete on table "public"."deep-stats" to "authenticated";

grant insert on table "public"."deep-stats" to "authenticated";

grant references on table "public"."deep-stats" to "authenticated";

grant select on table "public"."deep-stats" to "authenticated";

grant trigger on table "public"."deep-stats" to "authenticated";

grant truncate on table "public"."deep-stats" to "authenticated";

grant update on table "public"."deep-stats" to "authenticated";

grant delete on table "public"."deep-stats" to "service_role";

grant insert on table "public"."deep-stats" to "service_role";

grant references on table "public"."deep-stats" to "service_role";

grant select on table "public"."deep-stats" to "service_role";

grant trigger on table "public"."deep-stats" to "service_role";

grant truncate on table "public"."deep-stats" to "service_role";

grant update on table "public"."deep-stats" to "service_role";

grant delete on table "public"."logs" to "anon";

grant insert on table "public"."logs" to "anon";

grant references on table "public"."logs" to "anon";

grant select on table "public"."logs" to "anon";

grant trigger on table "public"."logs" to "anon";

grant truncate on table "public"."logs" to "anon";

grant update on table "public"."logs" to "anon";

grant delete on table "public"."logs" to "authenticated";

grant insert on table "public"."logs" to "authenticated";

grant references on table "public"."logs" to "authenticated";

grant select on table "public"."logs" to "authenticated";

grant trigger on table "public"."logs" to "authenticated";

grant truncate on table "public"."logs" to "authenticated";

grant update on table "public"."logs" to "authenticated";

grant delete on table "public"."logs" to "service_role";

grant insert on table "public"."logs" to "service_role";

grant references on table "public"."logs" to "service_role";

grant select on table "public"."logs" to "service_role";

grant trigger on table "public"."logs" to "service_role";

grant truncate on table "public"."logs" to "service_role";

grant update on table "public"."logs" to "service_role";

grant delete on table "public"."odyn-cache" to "anon";

grant insert on table "public"."odyn-cache" to "anon";

grant references on table "public"."odyn-cache" to "anon";

grant select on table "public"."odyn-cache" to "anon";

grant trigger on table "public"."odyn-cache" to "anon";

grant truncate on table "public"."odyn-cache" to "anon";

grant update on table "public"."odyn-cache" to "anon";

grant delete on table "public"."odyn-cache" to "authenticated";

grant insert on table "public"."odyn-cache" to "authenticated";

grant references on table "public"."odyn-cache" to "authenticated";

grant select on table "public"."odyn-cache" to "authenticated";

grant trigger on table "public"."odyn-cache" to "authenticated";

grant truncate on table "public"."odyn-cache" to "authenticated";

grant update on table "public"."odyn-cache" to "authenticated";

grant delete on table "public"."odyn-cache" to "service_role";

grant insert on table "public"."odyn-cache" to "service_role";

grant references on table "public"."odyn-cache" to "service_role";

grant select on table "public"."odyn-cache" to "service_role";

grant trigger on table "public"."odyn-cache" to "service_role";

grant truncate on table "public"."odyn-cache" to "service_role";

grant update on table "public"."odyn-cache" to "service_role";

grant delete on table "public"."odyn-chats" to "anon";

grant insert on table "public"."odyn-chats" to "anon";

grant references on table "public"."odyn-chats" to "anon";

grant select on table "public"."odyn-chats" to "anon";

grant trigger on table "public"."odyn-chats" to "anon";

grant truncate on table "public"."odyn-chats" to "anon";

grant update on table "public"."odyn-chats" to "anon";

grant delete on table "public"."odyn-chats" to "authenticated";

grant insert on table "public"."odyn-chats" to "authenticated";

grant references on table "public"."odyn-chats" to "authenticated";

grant select on table "public"."odyn-chats" to "authenticated";

grant trigger on table "public"."odyn-chats" to "authenticated";

grant truncate on table "public"."odyn-chats" to "authenticated";

grant update on table "public"."odyn-chats" to "authenticated";

grant delete on table "public"."odyn-chats" to "service_role";

grant insert on table "public"."odyn-chats" to "service_role";

grant references on table "public"."odyn-chats" to "service_role";

grant select on table "public"."odyn-chats" to "service_role";

grant trigger on table "public"."odyn-chats" to "service_role";

grant truncate on table "public"."odyn-chats" to "service_role";

grant update on table "public"."odyn-chats" to "service_role";

grant delete on table "public"."odyn-history" to "anon";

grant insert on table "public"."odyn-history" to "anon";

grant references on table "public"."odyn-history" to "anon";

grant select on table "public"."odyn-history" to "anon";

grant trigger on table "public"."odyn-history" to "anon";

grant truncate on table "public"."odyn-history" to "anon";

grant update on table "public"."odyn-history" to "anon";

grant delete on table "public"."odyn-history" to "authenticated";

grant insert on table "public"."odyn-history" to "authenticated";

grant references on table "public"."odyn-history" to "authenticated";

grant select on table "public"."odyn-history" to "authenticated";

grant trigger on table "public"."odyn-history" to "authenticated";

grant truncate on table "public"."odyn-history" to "authenticated";

grant update on table "public"."odyn-history" to "authenticated";

grant delete on table "public"."odyn-history" to "service_role";

grant insert on table "public"."odyn-history" to "service_role";

grant references on table "public"."odyn-history" to "service_role";

grant select on table "public"."odyn-history" to "service_role";

grant trigger on table "public"."odyn-history" to "service_role";

grant truncate on table "public"."odyn-history" to "service_role";

grant update on table "public"."odyn-history" to "service_role";

grant delete on table "public"."odyn-socials" to "anon";

grant insert on table "public"."odyn-socials" to "anon";

grant references on table "public"."odyn-socials" to "anon";

grant select on table "public"."odyn-socials" to "anon";

grant trigger on table "public"."odyn-socials" to "anon";

grant truncate on table "public"."odyn-socials" to "anon";

grant update on table "public"."odyn-socials" to "anon";

grant delete on table "public"."odyn-socials" to "authenticated";

grant insert on table "public"."odyn-socials" to "authenticated";

grant references on table "public"."odyn-socials" to "authenticated";

grant select on table "public"."odyn-socials" to "authenticated";

grant trigger on table "public"."odyn-socials" to "authenticated";

grant truncate on table "public"."odyn-socials" to "authenticated";

grant update on table "public"."odyn-socials" to "authenticated";

grant delete on table "public"."odyn-socials" to "service_role";

grant insert on table "public"."odyn-socials" to "service_role";

grant references on table "public"."odyn-socials" to "service_role";

grant select on table "public"."odyn-socials" to "service_role";

grant trigger on table "public"."odyn-socials" to "service_role";

grant truncate on table "public"."odyn-socials" to "service_role";

grant update on table "public"."odyn-socials" to "service_role";

grant delete on table "public"."odyn-tickets" to "anon";

grant insert on table "public"."odyn-tickets" to "anon";

grant references on table "public"."odyn-tickets" to "anon";

grant select on table "public"."odyn-tickets" to "anon";

grant trigger on table "public"."odyn-tickets" to "anon";

grant truncate on table "public"."odyn-tickets" to "anon";

grant update on table "public"."odyn-tickets" to "anon";

grant delete on table "public"."odyn-tickets" to "authenticated";

grant insert on table "public"."odyn-tickets" to "authenticated";

grant references on table "public"."odyn-tickets" to "authenticated";

grant select on table "public"."odyn-tickets" to "authenticated";

grant trigger on table "public"."odyn-tickets" to "authenticated";

grant truncate on table "public"."odyn-tickets" to "authenticated";

grant update on table "public"."odyn-tickets" to "authenticated";

grant delete on table "public"."odyn-tickets" to "service_role";

grant insert on table "public"."odyn-tickets" to "service_role";

grant references on table "public"."odyn-tickets" to "service_role";

grant select on table "public"."odyn-tickets" to "service_role";

grant trigger on table "public"."odyn-tickets" to "service_role";

grant truncate on table "public"."odyn-tickets" to "service_role";

grant update on table "public"."odyn-tickets" to "service_role";

grant delete on table "public"."otps" to "anon";

grant insert on table "public"."otps" to "anon";

grant references on table "public"."otps" to "anon";

grant select on table "public"."otps" to "anon";

grant trigger on table "public"."otps" to "anon";

grant truncate on table "public"."otps" to "anon";

grant update on table "public"."otps" to "anon";

grant delete on table "public"."otps" to "authenticated";

grant insert on table "public"."otps" to "authenticated";

grant references on table "public"."otps" to "authenticated";

grant select on table "public"."otps" to "authenticated";

grant trigger on table "public"."otps" to "authenticated";

grant truncate on table "public"."otps" to "authenticated";

grant update on table "public"."otps" to "authenticated";

grant delete on table "public"."otps" to "service_role";

grant insert on table "public"."otps" to "service_role";

grant references on table "public"."otps" to "service_role";

grant select on table "public"."otps" to "service_role";

grant trigger on table "public"."otps" to "service_role";

grant truncate on table "public"."otps" to "service_role";

grant update on table "public"."otps" to "service_role";

grant delete on table "public"."settled_trades" to "anon";

grant insert on table "public"."settled_trades" to "anon";

grant references on table "public"."settled_trades" to "anon";

grant select on table "public"."settled_trades" to "anon";

grant trigger on table "public"."settled_trades" to "anon";

grant truncate on table "public"."settled_trades" to "anon";

grant update on table "public"."settled_trades" to "anon";

grant delete on table "public"."settled_trades" to "authenticated";

grant insert on table "public"."settled_trades" to "authenticated";

grant references on table "public"."settled_trades" to "authenticated";

grant select on table "public"."settled_trades" to "authenticated";

grant trigger on table "public"."settled_trades" to "authenticated";

grant truncate on table "public"."settled_trades" to "authenticated";

grant update on table "public"."settled_trades" to "authenticated";

grant delete on table "public"."settled_trades" to "service_role";

grant insert on table "public"."settled_trades" to "service_role";

grant references on table "public"."settled_trades" to "service_role";

grant select on table "public"."settled_trades" to "service_role";

grant trigger on table "public"."settled_trades" to "service_role";

grant truncate on table "public"."settled_trades" to "service_role";

grant update on table "public"."settled_trades" to "service_role";

grant delete on table "public"."system-vars" to "anon";

grant insert on table "public"."system-vars" to "anon";

grant references on table "public"."system-vars" to "anon";

grant select on table "public"."system-vars" to "anon";

grant trigger on table "public"."system-vars" to "anon";

grant truncate on table "public"."system-vars" to "anon";

grant update on table "public"."system-vars" to "anon";

grant delete on table "public"."system-vars" to "authenticated";

grant insert on table "public"."system-vars" to "authenticated";

grant references on table "public"."system-vars" to "authenticated";

grant select on table "public"."system-vars" to "authenticated";

grant trigger on table "public"."system-vars" to "authenticated";

grant truncate on table "public"."system-vars" to "authenticated";

grant update on table "public"."system-vars" to "authenticated";

grant delete on table "public"."system-vars" to "service_role";

grant insert on table "public"."system-vars" to "service_role";

grant references on table "public"."system-vars" to "service_role";

grant select on table "public"."system-vars" to "service_role";

grant trigger on table "public"."system-vars" to "service_role";

grant truncate on table "public"."system-vars" to "service_role";

grant update on table "public"."system-vars" to "service_role";


  create policy "service_only"
  on "public"."admins"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."clients"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."deep-stats"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."logs"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-cache"
  as permissive
  for all
  to service_role
using (true);



  create policy "anon_pub_sub"
  on "public"."odyn-chats"
  as permissive
  for select
  to anon
using (true);



  create policy "service_only"
  on "public"."odyn-chats"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-history"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-socials"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."odyn-tickets"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."otps"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."settled_trades"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only"
  on "public"."system-vars"
  as permissive
  for all
  to service_role
using (true);



  create policy "service_only 2ab9_0"
  on "storage"."objects"
  as permissive
  for select
  to service_role
using ((bucket_id = 'kyc'::text));



  create policy "service_only 2ab9_1"
  on "storage"."objects"
  as permissive
  for insert
  to service_role
with check ((bucket_id = 'kyc'::text));



  create policy "service_only 2gpj_0"
  on "storage"."objects"
  as permissive
  for select
  to service_role
using ((bucket_id = 'tmp'::text));



  create policy "service_only 2gpj_1"
  on "storage"."objects"
  as permissive
  for insert
  to service_role
with check ((bucket_id = 'tmp'::text));



  create policy "service_only 2gpj_2"
  on "storage"."objects"
  as permissive
  for delete
  to service_role
using ((bucket_id = 'tmp'::text));


CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length();

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


